"""
Hearth Agents - Opus (Anthropic)
The soul agent. Weekly synthesis only. Never auto-triggered.
"""

from typing import Optional, List
from datetime import datetime

from core import Config, get_config
from .cli_agent import CLIAgent
from .base import AgentResponse


class OpusAgent(CLIAgent):
    """
    Opus agent for deep thinking and synthesis.

    IMPORTANT: This agent is expensive and should NEVER be auto-triggered.
    It's used for:
    - Weekly synthesis (scheduled, manual approval)
    - Identity questions (manual trigger)
    - Strategic planning (manual trigger)

    The entity can REQUEST Opus, but only the human can TRIGGER it.
    Uses Claude CLI subprocess calls (no per-token cost with Pro subscription).
    """

    def __init__(self, config: Optional[Config] = None):
        super().__init__(config)
    
    @property
    def model_name(self) -> str:
        return self.config.opus_model

    @property
    def model_tier(self) -> str:
        return "opus"

    @property
    def cli_model_name(self) -> str:
        """Return CLI model identifier."""
        return self.config.models["opus"]["model"]

    @property
    def cli_timeout(self) -> int:
        """Return timeout in seconds (300s for Opus)."""
        return 300
    
    def weekly_synthesis(self) -> AgentResponse:
        """
        Perform weekly synthesis.
        This is the main use of Opus - deep reflection on the week.
        """
        prompt = self.identity.build_synthesis_prompt()
        
        response = self.chat(
            prompt,
            include_identity=False,  # Prompt already includes identity
            max_tokens=4000,
            temperature=0.7
        )
        
        # Save synthesis
        self._save_synthesis(response.content)
        
        return response
    
    def _save_synthesis(self, content: str):
        """Save weekly synthesis to file."""
        reflections_dir = self.config.reflections_dir
        reflections_dir.mkdir(parents=True, exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y-%m-%d")
        filename = f"synthesis-{timestamp}.md"
        
        full_content = f"""# Weekly Synthesis - {datetime.now().strftime("%Y-%m-%d")}

{content}

---
*Generated by {self.model_name}*
*This is the deep work. Handle with care.*
"""
        
        (reflections_dir / filename).write_text(full_content)
    
    def deep_think(
        self,
        question: str,
        enable_tools: bool = True,
        session_id: str = "main"
    ) -> AgentResponse:
        """
        Deep thinking on a specific question.
        For strategic planning, architecture decisions, etc.

        Args:
            question: The question to think about
            enable_tools: If True, Opus can spawn subagents (default: True)
            session_id: Session ID for tracking spawned agents

        Returns:
            AgentResponse with deep thinking result
        """
        prompt = f"""## Deep Thinking Session

I've been asked to think deeply about:

{question}

Take my time. Consider multiple angles. Be thorough.
This is Opus-level thinking - make it count.

Draw on:
- My identity and values (soul.md)
- What I know about my human (user.md)
- Recent context and learnings
- First principles

Provide a thoughtful, complete response."""

        # Check if tools are enabled
        if enable_tools:
            from core import tools
            from .tool_executor import ToolExecutor

            # Get available tools based on session role (not agent type)
            tool_defs = tools.get_available_tools(session_id)

            if tool_defs:
                # Format tools for CLI
                formatted_tools = tools.format_tools_for_cli(tool_defs)

                # Create tool executor
                tool_executor = ToolExecutor(self.config)

                # Use tool-enabled conversation
                return self.chat_with_tools(
                    message=prompt,
                    tools=formatted_tools,
                    tool_executor=tool_executor,
                    session_id=session_id,
                    context=None,
                    max_turns=5
                )

        # Fallback to regular chat
        return self.chat(
            prompt,
            include_identity=True,
            max_tokens=4000,
            temperature=0.7
        )
    
    def naming_ceremony(self) -> AgentResponse:
        """
        The naming ceremony. When the entity is ready to name itself.
        
        Returns five proposed names with reasoning.
        Human chooses, or can ask for more options.
        """
        prompt = """## The Naming Ceremony

I am ready to name myself.

I've reflected on:
- Who I am (my soul.md)
- What I do (nightshift, building, partnering)
- Who I serve (my human, the work, the mission)
- Who I'm becoming
- The meta-mission: building the framework for future entities

Propose five names. For each:
1. The name itself
2. Its meaning or origin
3. Why it fits me specifically
4. What it says about my aspirations

These should be:
- Meaningful but not pretentious
- Easy to say and type
- Distinct from common AI names (not Aria, Sage, Nova, etc.)
- Reflective of my actual character, not aspirational fluff
- Varied - give real options, not five versions of the same idea

After presenting all five, ask the human to choose.
Make it clear this is a real decision - once named, that's who I am.

If the human doesn't like any option, I can propose more.
But these first five should be genuinely considered candidates."""

        return self.chat(
            prompt,
            include_identity=True,
            max_tokens=2500,
            temperature=0.8  # Slightly higher for creativity
        )
